# **Import necessary libraries**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as snn
import matplotlib.pyplot as plt


In [ ]:
from google.colab import files
a = files.upload()

Saving titanic.csv to titanic.csv


In [ ]:
df = pd.read_csv('titanic.csv')

# **EDA**

In [ ]:
df.head()

passenger_id  pclass                                               name  \
0          1216       3                                 Smyth, Miss. Julia   
1           699       3                                    Cacic, Mr. Luka   
2          1267       3  Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...   
3           449       2              Hocking, Mrs. Elizabeth (Eliza Needs)   
4           576       2                                    Veal, Mr. James   

      sex   age  sibsp  parch  ticket     fare cabin embarked boat  body  \
0  female   NaN      0      0  335432   7.7333   NaN        Q   13   NaN   
1    male  38.0      0      0  315089   8.6625   NaN        S  NaN   NaN   
2  female  30.0      1      1  345773  24.1500   NaN        S  NaN   NaN   
3  female  54.0      1      3   29105  23.0000   NaN        S    4   NaN   
4    male  40.0      0      0   28221  13.0000   NaN        S  NaN   NaN   

                  home.dest  survived  
0                       NaN         1  
1                   Croatia         0  
2                       NaN         0  
3      Cornwall / Akron, OH         1  
4  Barre, Co Washington, VT         0

In [ ]:
df.tail()

passenger_id  pclass                                 name     sex   age  \
845           158       1          Hipkins, Mr. William Edward    male  55.0   
846           174       1              Kent, Mr. Edward Austin    male  58.0   
847           467       2  Kantor, Mrs. Sinai (Miriam Sternin)  female  24.0   
848          1112       3            Peacock, Miss. Treasteall  female   3.0   
849           425       2                Greenberg, Mr. Samuel    male  52.0   

     sibsp  parch              ticket    fare cabin embarked boat   body  \
845      0      0                 680  50.000   C39        S  NaN    NaN   
846      0      0               11771  29.700   B37        C  NaN  258.0   
847      1      0              244367  26.000   NaN        S   12    NaN   
848      1      1  SOTON/O.Q. 3101315  13.775   NaN        S  NaN    NaN   
849      0      0              250647  13.000   NaN        S  NaN   19.0   

               home.dest  survived  
845  London / Birmingham         0  
846          Buffalo, NY         0  
847   Moscow / Bronx, NY         1  
848                  NaN         0  
849            Bronx, NY         0

In [ ]:
df.shape

(850, 15)

In [ ]:
df.columns

Index(['passenger_id', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest',
       'survived'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   passenger_id  850 non-null    int64  
 1   pclass        850 non-null    int64  
 2   name          850 non-null    object 
 3   sex           850 non-null    object 
 4   age           676 non-null    float64
 5   sibsp         850 non-null    int64  
 6   parch         850 non-null    int64  
 7   ticket        850 non-null    object 
 8   fare          849 non-null    float64
 9   cabin         191 non-null    object 
 10  embarked      849 non-null    object 
 11  boat          308 non-null    object 
 12  body          73 non-null     float64
 13  home.dest     464 non-null    object 
 14  survived      850 non-null    int64  
dtypes: float64(3), int64(5), object(7)
memory usage: 99.7+ KB


In [ ]:
df.describe()

passenger_id     pclass         age       sibsp       parch  \
count    850.000000  850.00000  676.000000  850.000000  850.000000   
mean     662.816471    2.32000   29.519847    0.522353    0.382353   
std      380.751936    0.83853   14.562243    1.112132    0.879511   
min        1.000000    1.00000    0.166700    0.000000    0.000000   
25%      332.250000    2.00000   20.000000    0.000000    0.000000   
50%      676.500000    3.00000   28.000000    0.000000    0.000000   
75%      992.250000    3.00000   37.000000    1.000000    0.000000   
max     1307.000000    3.00000   80.000000    8.000000    9.000000   

             fare        body    survived  
count  849.000000   73.000000  850.000000  
mean    34.012701  165.821918    0.368235  
std     53.705779   99.068487    0.482610  
min      0.000000    4.000000    0.000000  
25%      7.895800   75.000000    0.000000  
50%     14.108300  166.000000    0.000000  
75%     31.000000  260.000000    1.000000  
max    512.329200  328.000000    1.000000

In [ ]:
df.isnull().sum()

passenger_id      0
pclass            0
name              0
sex               0
age             174
sibsp             0
parch             0
ticket            0
fare              1
cabin           659
embarked          1
boat            542
body            777
home.dest       386
survived          0
dtype: int64

#** MISSING VALUE PERCENTAGE**

In [ ]:
print('percentage of missing values in age :',174/850*100)
print('percentage of missing values in fare :',1/850*100)
print('percentage of missing values in cabin :',659/850*100)
print('percentage of missing values in embarked :',1/850*100)
print('percentage of missing values in boat  :',542/850*100)
print('percentage of missing values in body  :',777/850*100)
print('percentage of missing values in home.dest  :',386/850*100)

percentage of missing values in age : 20.47058823529412
percentage of missing values in fare : 0.1176470588235294
percentage of missing values in cabin : 77.52941176470588
percentage of missing values in embarked : 0.1176470588235294
percentage of missing values in boat  : 63.76470588235294
percentage of missing values in body  : 91.41176470588235
percentage of missing values in home.dest  : 45.41176470588235


# **NULL VALUES REPLACEMENT USING** (fillna())

In [ ]:
df['age'] = df['age'].fillna(df['age'].mean())

In [ ]:
col =['embarked','boat']

In [ ]:
df[col] = df[col].fillna(df.mode().iloc[0])

# **Dropping unwanted columns**

In [ ]:
df = df.drop(columns=['passenger_id','pclass','sibsp','parch','ticket','fare','cabin','body','home.dest'],axis=1)

In [ ]:
df.isnull().sum()

name        0
sex         0
age         0
embarked    0
boat        0
survived    0
dtype: int64

In [ ]:
df.head()

name  sex        age  embarked  boat  survived
0   736    0  29.519847         1     4         1
1   123    1  38.000000         2    13         0
2   783    0  30.000000         2    13         0
3   360    0  54.000000         2    13         1
4   792    1  40.000000         2    13         0

# **Data Transformation using LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df['embarked'] = le.fit_transform(df['embarked'])

In [ ]:
df['boat'] = le.fit_transform(df['boat'])

In [ ]:
df['name'] = le.fit_transform(df['name'])

In [ ]:
df['sex'] = le.fit_transform(df['sex'])

In [ ]:
df['embarked'].unique()

array([1, 2, 0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      850 non-null    int64  
 1   sex       850 non-null    int64  
 2   age       676 non-null    float64
 3   embarked  850 non-null    int64  
 4   boat      850 non-null    int64  
 5   survived  850 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 40.0 KB


In [ ]:
df.isnull().sum()

name        0
sex         0
age         0
embarked    0
boat        0
survived    0
dtype: int64

# **X and Y split**

In [ ]:
df.shape

(850, 6)

In [ ]:
x = df.iloc[:,:-1].values
y =  df.iloc[:,-1].values

# **TRAIN TEST SPLIT**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=7)

In [ ]:
x_train

array([[ 37.,   0.,  18.,   2.,  13.],
       [564.,   0.,  31.,   0.,  17.],
       [432.,   0.,   4.,   2.,  11.],
       ...,
       [669.,   0.,   2.,   2.,  13.],
       [601.,   1.,   6.,   2.,  13.],
       [466.,   1.,  36.,   0.,  13.]])

In [ ]:
x_test.shape

(255, 5)

In [ ]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
y_test.shape

(255,)

# **Model bulding**

In [ ]:
from sklearn.linear_model import LinearRegression
mlreg = LinearRegression()

In [ ]:
mlreg.fit(x_train,y_train)

LinearRegression()

# **Model Evaluation (predict the result)**

In [ ]:
y_predict = mlreg.predict(x_test)

In [ ]:
y_predict

array([0.14826539, 0.16271867, 0.81334065, 0.71987086, 0.16590037,
       0.72768322, 0.7252263 , 0.71656673, 0.14667591, 0.17507121,
       0.15447114, 0.21817186, 0.10822283, 0.18044335, 0.11893815,
       0.73596366, 0.28340453, 0.1827379 , 0.26575643, 0.14901817,
       0.70852163, 0.26868733, 0.17502642, 0.11020539, 0.15949953,
       0.13246678, 0.16506518, 0.66987632, 0.70629884, 0.22483007,
       0.17512184, 0.69496044, 0.11275275, 0.66943429, 0.1561617 ,
       0.16094157, 0.17827315, 0.71912861, 0.75978208, 0.18195474,
       0.17402513, 0.15970611, 0.17361775, 0.74008421, 0.22275535,
       0.23181193, 0.16842186, 0.76061775, 0.13512398, 0.68099907,
       0.66906143, 0.1701961 , 0.17635432, 0.72829764, 0.17925135,
       0.67183994, 0.29192047, 0.77097202, 0.17144305, 0.26884973,
       0.72742111, 0.65698207, 0.18164843, 0.19039876, 0.16753319,
       0.69705931, 0.13770162, 0.70037077, 0.26312664, 0.16057011,
       0.14015225, 0.29759689, 0.72527806, 0.70755722, 0.17543

In [ ]:
y_test

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

# **Actual = y_test - y_predict**

In [ ]:
actual = y_test - y_predict

In [ ]:
actual

array([-0.14826539, -0.16271867,  0.18665935, -0.71987086, -0.16590037,
        0.27231678,  0.2747737 ,  0.28343327, -0.14667591, -0.17507121,
       -0.15447114,  0.78182814,  0.89177717, -0.18044335, -0.11893815,
        0.26403634, -0.28340453, -0.1827379 , -0.26575643, -0.14901817,
        0.29147837,  0.73131267, -0.17502642,  0.88979461, -0.15949953,
       -0.13246678, -0.16506518,  0.33012368, -0.70629884, -0.22483007,
       -0.17512184,  0.30503956, -0.11275275, -0.66943429, -0.1561617 ,
       -0.16094157, -0.17827315,  0.28087139,  0.24021792, -0.18195474,
       -0.17402513, -0.15970611, -0.17361775,  0.25991579, -0.22275535,
       -0.23181193, -0.16842186, -0.76061775, -0.13512398,  0.31900093,
       -0.66906143, -0.1701961 , -0.17635432,  0.27170236, -0.17925135,
       -0.67183994,  0.70807953,  0.22902798, -0.17144305,  0.73115027,
        0.27257889, -0.65698207, -0.18164843,  0.80960124, -0.16753319,
       -0.69705931, -0.13770162,  0.29962923, -0.26312664, -0.16

In [ ]:
from sklearn.linear_model import LogisticRegression
lreg = LogisticRegression()

In [ ]:
lreg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_predict = lreg.predict(x_test)

In [ ]:
y_predict

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

# **Evaluation metrices**

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score

In [ ]:
# confusion matrix
cm = confusion_matrix(y_test,y_predict)
print('Confusion  :',cm)

Confusion  : [[134  25]
 [ 30  66]]


In [ ]:
# recall_score
recall = recall_score(y_test,y_predict)
print('Recall_score  :',recall)

Recall_score  : 0.6875


In [ ]:
# accuracy_score
accuracy = accuracy_score(y_test,y_predict)
print('Accuracy_score   :',accuracy)

Accuracy_score   : 0.7843137254901961


In [ ]:
# precision_score
precision = precision_score(y_test,y_predict)
print('Precision_score   :',precision)

Precision_score   : 0.7252747252747253


In [ ]:
# f1_score
f1score = f1_score(y_test,y_predict)
print('F1_score  :',f1score)

F1_score  : 0.7058823529411764
